PORT = 54321
PLAYER_LIMIT = 100

INITIAL_RADIUS = 20
INITIAL_SPEED = 1
CELL_RADIUS = 10
MINIMUM_RADIUS = 5

MAP_WIDTH = 800 #*5
MAP_HEIGHT = 600 #*5

GRID_SIZE = CELL_RADIUS*4
GRID_COLS = MAP_WIDTH // GRID_SIZE
GRID_ROWS = MAP_HEIGHT // GRID_SIZE

NUMBER_OF_CELLS = 10
MASS_LOSS_TIME = 5

MAX_DATA_SIZE = 64  # eat;IDDDD,XXXXX.XX,YYYYY.YY,VXXXX.VX,VYYYY,VY
AVAILABLE_COMMANDS = ('start', 'move', 'get', 'eat', 'disconnect', 'update', 'kick', 'error')