PORT = 54321
PLAYER_LIMIT = 100

INITIAL_RADIUS = 60.0
INITIAL_SPEED = 1
CELL_RADIUS = 10.0
MINIMUM_RADIUS = 5.0

MAP_WIDTH = 800 #*5
MAP_HEIGHT = 600 #*5

GRID_SIZE = CELL_RADIUS*4
GRID_COLS = MAP_WIDTH // GRID_SIZE
GRID_ROWS = MAP_HEIGHT // GRID_SIZE

NUMBER_OF_CELLS = 100
MASS_LOSS_TIME = 5

MAX_RECV_DATA_SIZE = 256  # eat;XXXXX.XX,YYYYY.YY,RRRRR.RR,IDDDD,...
MAX_SEND_DATA_SIZE = 2048
AVAILABLE_COMMANDS = ('start', 'move', 'get', 'eat', 'disconnect', 'update', 'kick', 'error')