from pygario.vector import Vector2D
from pygame.font import Font

INITIAL_RADIUS = 20
INITIAL_SPEED = 1
CELL_RADIUS = 5

WINDOW_WIDTH = 200 # 1600
WINDOW_HEIGHT = 100 # 900
CENTER_WIDTH = WINDOW_WIDTH/2
CENTER_HEIGHT = WINDOW_HEIGHT/2

MAP_WIDTH = WINDOW_WIDTH*2
MAP_HEIGHT = WINDOW_HEIGHT*2

GRID_SIZE = CELL_RADIUS*4
GRID_COLS = MAP_WIDTH // GRID_SIZE
GRID_ROWS = MAP_HEIGHT // GRID_SIZE

NUMBER_OF_CELLS = 10 # 1000

Mouse = Vector2D(WINDOW_WIDTH/2, WINDOW_HEIGHT/2)
