from pygario.vector import Vector2D
from pygame.font import Font

INITIAL_RADIUS = 60
INITIAL_SPEED = 1
CELL_RADIUS = 10
MINIMUM_RADIUS = 5

WINDOW_WIDTH = 800 # 1600
WINDOW_HEIGHT = 600 # 900
CENTER_WIDTH = WINDOW_WIDTH/2
CENTER_HEIGHT = WINDOW_HEIGHT/2

MAP_WIDTH = WINDOW_WIDTH #*5
MAP_HEIGHT = WINDOW_HEIGHT #*5

GRID_SIZE = CELL_RADIUS*4
GRID_COLS = MAP_WIDTH // GRID_SIZE
GRID_ROWS = MAP_HEIGHT // GRID_SIZE

NUMBER_OF_CELLS = 2000

SCALE_MULTIPLIER = 0.05

# Network values
PORT = 54321
MAX_DATA_SIZE = 2048*20
AVAILABLE_COMMANDS = ('update', 'kick', 'error', 'ok')
